import Head from 'next/head';
import { Typography, Row, Col, Input, Button, Form } from 'antd';
import Router from 'next/router';

const { Title } = Typography;

export default function Home() {
  const onFinishHandler = (data): void => {
    console.log(data);
    Router.push('/jobs');
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Row className='container' align='top' justify='center' style={{ marginTop: '4em' }}>
        <Col span={12}>
          <img src='/loggedout/main.svg' style={{ height: 300 }} />
        </Col>
        <Col span={6}>
          <Title level={4}>Employer Login/Sign Up</Title>
          <Form
            name="login"
            layout='vertical'
            requiredMark={false}
            onFinish={onFinishHandler}
          >
            <Form.Item
              label=""
              name="mobile"
              rules={[{ required: true, message: 'Please input your mobile number!' }]}
            >
              <Input addonBefore="+91" placeholder='Please enter the phone number' />
              {/* <Input /> */}
            </Form.Item>
            <Form.Item>
              <Button block type='primary' htmlType="submit">Login to Job Platform</Button>
            </Form.Item>
          </Form>
        </Col>
      </Row>
    </div>
  )
}
